framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            outbox: '%env(OUTBOX_TRANSPORT_DSN)%'
            failed: '%env(OUTBOX_FAILED_TRANSPORT_DSN)%'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\EventInterface': outbox
